decay	0
production_cut	0.1
quartz_thickness	20.0
do_segmentize	1
wrapper_thickness	1.0
particle	anti_proton
momentum	0.735
wrap_type	2
quartz_finish	0
input_beam_file	beam/beam_K_seg1_run00348.root
air_layer_thickness	0.0
qe_scale	1.37
teflon_reflectivity_scale	1.0
teflon_sigma_alpha	1.65
teflon_specularSpike	0.0
teflon_specularLobe	0.0
teflon_backScatter	0.0
teflon_diffuseLobe	1.0
ej510_sigma_alpha	0.15
ej510_specularSpike	0.0
ej510_specularLobe	0.0
ej510_backScatter	0.0
ej510_diffuseLobe	1.0
Quartz_A_Alpha	0.01
Quartz_B_Alpha	0.18
quartz_boundary_reflectivity	1.0
quartz_specularSpike	1.0
quartz_specularLobe	0.0
quartz_backScatter	0.0
quartz_diffuseLobe	0.0
beam_y_offset	-10.45
quartz_abs_scale	1.0
